---
## hash are not really useful as files are updated regulary but if needed.
    - name: Maxmind directory
      file: path=/var/maxmind mode=0755 owner=root state=directory
    - stat: path=/var/maxmind/GeoIP.dat
      register: db1
    - name: Get Maxmind db
      get_url: url=http://geolite.maxmind.com/download/geoip/database/GeoLiteCountry/GeoIP.dat.gz
        dest=/var/maxmind/GeoIP.dat.gz
        mode=0444
#        sha256sum=840f0d7c7beb3ae923db34644011cb3569360d08bdd5b45d994baff293d8835e
      when: not db1.stat.exists
    - stat: path=/var/maxmind/GeoIPv6.dat
      register: db2
    - name: Get Maxmind db
      get_url: url=http://geolite.maxmind.com/download/geoip/database/GeoIPv6.dat.gz
        dest=/var/maxmind/GeoIPv6.dat.gz
        mode=0444
#        sha256sum=f4e3788703046aeea660988eeb322ec0d772674179e8400947f95fbe779a1f65
      when: not db2.stat.exists
    - stat: path=/var/maxmind/GeoLiteCity.dat
      register: db3
    - name: Get Maxmind db
      get_url: url=http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz
        dest=/var/maxmind/GeoLiteCity.dat.gz
        mode=0444
#        sha256sum=4b135aa121b658e5659382ddb392066d18da0508a21ffe9192d576e6e8946273
      when: not db3.stat.exists
    - stat: path=/var/maxmind/GeoLiteCityv6.dat
      register: db4
    - name: Get Maxmind db
      get_url: url=http://geolite.maxmind.com/download/geoip/database/GeoLiteCityv6-beta/GeoLiteCityv6.dat.gz
        dest=/var/maxmind/GeoLiteCityv6.dat.gz
        mode=0444
#        sha256sum=7a53044aa2d135eadbd969473200d2d5992e2db1d84e39809421d740a53f2e1c
      when: not db4.stat.exists
    - stat: path=/var/maxmind/GeoIPASNum.dat
      register: db5
    - name: Get Maxmind db
      get_url: url=http://geolite.maxmind.com/download/geoip/database/asnum/GeoIPASNum.dat.gz
        dest=/var/maxmind/GeoIPASNum.dat.gz
        mode=0444
#        sha256sum=ee72c32aeff0251cea3b757c93a64e7386f19de5e223bd39ddde02ed8b062467
      when: not db5.stat.exists
    - stat: path=/var/maxmind/GeoIPASNumv6.dat
      register: db6
    - name: Get Maxmind db
      get_url: url=http://geolite.maxmind.com/download/geoip/database/asnum/GeoIPASNumv6.dat.gz
        dest=/var/maxmind/GeoIPASNumv6.dat.gz
        mode=0444
#        sha256sum=c9464a150567d28dc58e283328bbb802946b704596d99f12a6a0f91e5e2f1057
      when: not db6.stat.exists
    - name: extract db
      command: gunzip /var/maxmind/{{ item }}.gz
      with_items:
        - GeoIP.dat
        - GeoIPv6.dat
        - GeoLiteCity.dat
        - GeoLiteCityv6.dat
        - GeoIPASNum.dat
        - GeoIPASNumv6.dat
      when: not db1.stat.exists

    - copy: src=update-maxmind.sh dest=/usr/local/bin/update-maxmind.sh mode=0755
    - name: apt | ensure cron is installed
      apt: name=cron state=present
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    - name: yum | ensure cron is installed
      yum: name=crontabs state=present
      when: ansible_os_family == "RedHat" or ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

    - name: cron task to update daily
      cron: name="maxmind autoupdate" minute=0 hour=0
            user=root job="/usr/local/bin/update-maxmind.sh > /tmp/update_maxmind.log 2>&1"

